---
- name: Download and unpack tarball
  unarchive:
    src: "{{ hadoop_software_url }}"
    dest: /home/hadoop
    creates: "/home/hadoop/{{ hadoop_software_url | basename }}"
    copy: no

- name: Create symlink to directory
  file: dest=~hadoop/hadoop src="~hadoop/{{ hadoop_software_url | basename | splitext | first | splitext | first }}" state=link
#"

- name: Adding environemnt configuration 
  lineinfile:
    dest: /home/hadoop/.bashrc
    line: export {{ item }}
  with_items:
    - HADOOP_INSTALL=/home/hadoop/hadoop
    - HADOOP_CONF_DIR=${HADOOP_INSTALL}/etc/hadoop
    - PATH=$PATH:${HADOOP_INSTALL}/bin
