---
- name: Download and unpack tarball
  unarchive:
    src: "{{ hadoop_software_url }}"
    dest: /home/hadoop
    creates: "/home/hadoop/{{ hadoop_software_url | basename }}"
    copy: no

- name: Create symlink to directory
  file: dest=~hadoop/hadoop src="~hadoop/{{ hadoop_software_url | basename | splitext | first | splitext | first }}" state=link
#"

- name: Adding environment configuration 
  lineinfile:
    dest: /home/hadoop/.bashrc
    line: "{{ item.env }}"
    regexp: "{{ item.regex | default('^{{ item.env }}$') }}"
  with_items:
    - env: export HADOOP_INSTALL=/home/hadoop/hadoop
      regex: ^export HADOOP_INSTALL
    - env: export HADOOP_CONF_DIR=${HADOOP_INSTALL}/etc/hadoop
      regex: ^export HADOOP_CONF_DIR
    - env: export PATH=$PATH:${HADOOP_INSTALL}/bin:${HADOOP_INSTALL}/sbin

- name: Hadoop configuration files
  template: src={{ item }}.j2 dest=~hadoop/hadoop/etc/hadoop/{{ item }} mode=0644
  with_items:
    - mapred-site.xml
    - core-site.xml
    - yarn-site.xml
    - hdfs-site.xml
    - slaves
