---
- name: Requirements for all Hadoop nodes
  hosts: hadoop
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  tags: config
  roles:
    - openjdk8
    - hadoop_hosts_file

- name: Requirements for Hadoop masters
  hosts: hadoop_master_nodes
  remote_user: ubuntu
  become: yes
  tags: config
  roles:
    - hadoop_master_user
  tasks:
    - name: Copy SSH pub key from master
      shell: cat ~hadoop/.ssh/id_*.pub
      register: master_pubkey
      changed_when: False

- name: Requirements for Hadoop data nodes
  hosts: hadoop_data_nodes
  remote_user: ubuntu
  become: yes
  tags: config
  vars:
    - master_pubkey: "{{ hostvars[groups['hadoop_master_nodes'][0]].master_pubkey.stdout }}"
  roles:
    - hadoop_slave_user

- name: Installation for Hadoop nodes
  hosts: hadoop
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  become_user: hadoop
  tags: config
  vars:
    hadoop_version: 2.7.1
  roles:
    - hadoop_software
